<footer class="footer">
	<div class="row">
		<div class="column">
			<h3>Contact</h3>
			<p>101217869@swin.edu.au</p>
			<p>(+61)0401037123</p>
			<p>Swinburne University of Technology Hawthorn Campus,
			<br/>
			<br />Melbourne Australia</p>
			<div class="bottom-bar">
     <p> 2020 Copyright © MusicIsLife Store. All Rights Reserved </p>
	  </div>
		</div>
		
		<div class="column">
			<h3>Navigate</h3>
				<ul class="footer-links">
					<li><a href="product.html">Product</a></li>
					<li><a href="enquire.html">Enquiry</a></li>
					<li><a href="about.html">About Me</a></li>
					<li><a href="enhancements.html">Enhancements</a></li>
				</ul>
		</div>
		
			<div class="column">
			<h4>Connect</h4>
			<a class="facebook" href="https://www.facebook.com">
				<i class="fa fa-facebook-square"> </i>
			</a>	
			<a class="twitter" href="https://www.twitter.com">
				<i class="fa fa-twitter-square"> </i>
			</a>
			<a class="instagram" href="https://www.instagram.com">
				<i class="fa fa-instagram"> </i>
			</a>
			
		</div>
		
		
	
		
	  </div>
	 </footer>