	<header class="header">
		<div class="nav-bar" id="myNavBar">
	<p><a class="logo" href ="index.html">
		<img src="images/logo.jfif" alt="Logo" />
	</a>
	</p>
	<p>
	<a href="index.php">Home</a>
	<a href="product.php">Product</a>
	<a href="enquire.php" >Enquiry</a>
	<a href="about.html" class="active">About Me</a>
	<a href="enhancements.html" >Enhancements</a>
	<a href="managers.php" >Manage Order</a>

	</p>
</div>
	</header>